# Generated by Django 5.0.5 on 2024-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrollen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=300, unique=True)),
                ('datum', models.DateField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=33, unique=True)),
            ],
        ),
    ]
