# Generated by Django 5.0.5 on 2024-05-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erstellte_kontrollen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kontrollen',
        ),
    ]
