# Generated by Django 5.0.4 on 2024-05-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrollen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('identifier', models.CharField(default='', help_text='Name, welchen die Python Dateien besitzen', max_length=300)),
                ('fach', models.CharField(default='Mathematik', max_length=100)),
                ('jahrgang', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
