# Generated by Django 5.0.5 on 2024-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrollen',
            name='identifier',
            field=models.CharField(default='', help_text='Name, welchen die Python Dateien besitzen', max_length=300, unique=True),
        ),
    ]
