# Generated by Django 5.0.5 on 2024-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollen', '0004_alter_erstelltekontrollen_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrollen',
            name='thema',
            field=models.CharField(default='', max_length=150),
        ),
    ]
