# Generated by Django 5.0.5 on 2024-05-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollen', '0005_kontrollen_thema'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrollen',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
