# Generated by Django 5.0.5 on 2024-05-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollen', '0006_kontrollen_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrollen',
            old_name='visibility',
            new_name='sichtbar',
        ),
    ]
